### ISSUE TITLE
Archiving error with bicode enabled

### ISSUE THREAD

**Issue by asifmimi1** [loopsocial/firework_ios_sdk#4]
i am getting this error while trying to Archive my app with Bitcode enable, tried some stackoverflow ideas but didn't help, any ideas?

<img width="735" alt="Untitled" src="https://user-images.githubusercontent.com/30404856/138663311-86042b1e-9eb5-4fef-b2ad-5a123843efa2.png">

**Comment by spookyd** [comment]
Closing issue because it was reported to be resolved by updating Xcode version.
